default: &default
  adapter: postgresql
  encoding: utf8
  host: "localhost"
  username: postgres
  password: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: marketing_rails_development

test:
  <<: *default
  database: marketing_rails_test

production:
  <<: *default
  database: <%= ENV["DATABASE"] %>
  username: <%= ENV["USERNAME"] %>
  password: <%= ENV["PASSWORD"] %>
